import React,{useEffect,useState} from "react";
import {useApp} from "../context/AppContext";

export default function Profile(){
 const {currentUser,updateProfile}=useApp(); const [saved,setSaved]=useState(false); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [f,setF]=useState({name:"",phone:"",email:"",address:"",city:"",pincode:""});
 useEffect(()=>{if(currentUser)setF({name:currentUser.name||"",phone:currentUser.phone||"",email:currentUser.email||"",address:currentUser.address||"",city:currentUser.city||"",pincode:currentUser.pincode||""})},[currentUser]);
 if(!currentUser) return null;
 const submit=async e=>{e.preventDefault();setError("");setBusy(true);try{await updateProfile(f);setSaved(true);setTimeout(()=>setSaved(false),1800)}catch(x){setError(x.message)}finally{setBusy(false)}};
 return <main className="page"><div className="container"><div className="page-head"><span className="eyebrow">ACCOUNT</span><h1>My profile</h1><p>Your saved details are stored securely in Supabase.</p></div><div className="form-card profile-card"><div className="avatar">{currentUser.name?.charAt(0).toUpperCase()}</div>{saved&&<div className="alert alert-success">Profile updated.</div>}{error&&<div className="alert alert-danger">{error}</div>}<form onSubmit={submit}><label>Name<input className="form-control" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Phone<input className="form-control" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>Email<input type="email" className="form-control" value={f.email} disabled/></label><label>Address<textarea className="form-control" rows="3" value={f.address} onChange={e=>setF({...f,address:e.target.value})}/></label><div className="row g-3"><div className="col-md-6"><label>City<input className="form-control" value={f.city} onChange={e=>setF({...f,city:e.target.value})}/></label></div><div className="col-md-6"><label>PIN code<input className="form-control" pattern="[0-9]{6}" value={f.pincode} onChange={e=>setF({...f,pincode:e.target.value})}/></label></div></div><button disabled={busy} className="btn btn-success rounded-pill px-4">{busy?"Saving…":"Save changes"}</button></form></div></div></main>
}
